### ISSUE TITLE
現在の画面表示について

### ISSUE THREAD

**Issue by light-sugar** [light-sugar/2023_management_system#4]
初歩的すぎてごめんなさい。
とても根本的なところになるのですが、根本的すぎて調べても分からないので質問させてください！

今、わたしが行なっている作業は、例えばcontrollerの一覧で言うと
    // 同期処理で使っていたreturn部分
    return view('plist', compact('products', 'companies'));
部分を活性化させた状態で画面表示をしています。
まず,この表示でlaravelの画面表示が見えているブラウザでの修正作業を行う、で間違いないですか？

また、pullrequestの最後の方で指摘していただいた、ajaxのレスポンスを見てみてくださいの部分は、
// ajaxを使ってjsonで返したい！！
        $data = [
            'products' => $products,
            'companies' => $companies,
        ];
        return response()->json(
            [
                'products' => [
                'data' => $products->items(),
                'links' => $products->links()->toHtml()
                ],
                'companies' => $companies,
            ]
        );
このjsonでレスポンスを返すようにした部分を活性化させるであっていますか？

jsonでレスポンスを返した成功だった時がどのような画面になるのか分からないです。
今の真っ黒画面に文字列だけびっしり返しているものでいいのか、
それともブラウザ表示は同期処理の時のままで、
検証で出したコンソールにレスポンスの中身が返ってくるのでしょうか？？

**Comment by Kei-Miyamoto** [comment]
すみません…前者の質問の回答になっているか微妙ですが……
例えば、/plistの場合、
plistのブレードを表示させたいですよね?
そのためには、web.phpの/plistにあたるメソッドを経由してブレードを指定したり、変数等渡しています。なので、現時点/plistにアクセスした時上手く動いていないようでしたら、怪しいのは/plistを表示するためのメソッドや、plistブレードとそれに対応するjsファイルやcssファイルになります。(ざっくりですが)

**Comment by Kei-Miyamoto** [comment]
2つ目ですが、今あげてくださったのはshowListメソッド?ですよね?!

検索ボタン押下時の挙動なので、searchメソッドを見るが正しいです!
なので今ある形のreturn response()〜〜〜部分で問題ありません。

端的に言うと、成功した場合は
初期画面と同じような画面になるはずです🤔
(絞り込まれた対象のみ表示される)

php側でちゃんと値が返っているかどうかは、
ajax.jsの検索Ajax内のdoneでコンソールに出せば分かります。
もし表示が上手くいっていないのであれば、
Ajax側のHTML埋め込みが上手くいってないのかな?と思いますがどうでしょうか。

**Comment by light-sugar** [comment]
returnは、それぞれ1つずつが正解だと思うのですが、
今はjsonで返すと文字列だけが返ってくるので、どこを見ればいいのか分からず
return viewと切り替えながら作業を行なっています。

その返ってきている文字列というのも、添付しているような状態での画面全体にどーんと出ます。
宮本さんからコンソールの見本で送っていただいたような、ブラウザ表示は今のままでコンソールを見るとjsonのレスポンスができている状態が成功だと思うので、考え方のヒントを知りたいです！

![2023-04-13 9 48のイメージ](https://user-images.githubusercontent.com/115693283/231619800-0e0bfaa2-e739-438c-92fc-fe23ac30a2b5.JPG)
